### PR TITLE
Change composer requirements to allow magento 2.3

### PR DESCRIPTION
**Pull request by lracicot**
This PR aim to fix issue #138. It makes the module installable in Magento 2.3 but no tests have been executed to ensure that all functionalities are working.

### CODE REVIEW

**Comment by shochdoerfer** [comment]
Making the module installable in 2.3 is great, but does it work? "no tests have been executed to ensure that all functionalities are working" sounds a bit wired to me, I hope it's just a typo :)

**Comment by lracicot** [comment]
It worked well for my use case but I haven't had the time to verify all the features.

**Comment by shochdoerfer** [comment]
Tests seem to fail:
```
PHP Fatal error:  Class Mock_StoreInterface_f790d040 contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Magento\Store\Api\Data\StoreInterface::setIsActive, Magento\Store\Api\Data\StoreInterface::getIsActive) in magento2-force-login/vendor/phpunit/phpunit-mock-objects/src/Generator.php(264) : eval()'d code on line 1
```

Need to dig deeper but currently lacking a bit the time to do that. If you can assist fixing the tests, I'd be happy :)

**Comment by Noewt** [comment]
Downloaded the release manually and applied the 3 editted files (travis and the 2 composer files). Only error I got was while running di:compile

PHP Fatal error: Class 'BitExpert\ForceCustomerLogin\Controller\Adminhtml\Manage\Create' not found in BitExpert/ForceCustomerLogin/Controller/Adminhtml/Manage/Edit.php on line 19

Got this fixed by capitalising the B in the bitExpert folder

Module seems to be running smoothly on 2.3

**Comment by shochdoerfer** [comment]
Thank you @lracicot for your contribution!

**Pull request merged**
