### PR TITLE
Add module enabled check to plugin enabled

### LINKED ISSUE #182: Module not enabled but redirect to homepage
If we choose enabled NO on admin, having errors login in redirect visitor to homepage instead of staying on customer/account/login page

Steps to reproduce :
enable module via SSH
choose NO on backend config for enabled option
going to /customer/account/login
email : nonexistantmail@nowhere.com
password : anything

expected results : 
- error message on customer/account/login

Actual results : 
- visitor is redirected to homepage and error message appears here.

### PR DESCRIPTION
**Pull request by rikwillems**
Fixes #182

### CODE REVIEW

**Comment by shochdoerfer** [comment]
Thx @rikwillems for helping out!

**Comment by rikwillems** [comment]
@shochdoerfer you're welcome! Not sure what to make of the pipeline issues though. 

`Error: Ignored error pattern ~Parameter #3 \$data of method~ in path /home/runner/work/magento2-force-login/magento2-force-login/Block/Adminhtml/Manage/Create.php was not matched in reported errors.`
This seems to be an ignore that can be removed.

`Error: Method BitExpert\ForceCustomerLogin\Controller\LoginRouter::match() should return Magento\Framework\App\ActionInterface|void but returns Magento\Framework\App\Action.`
This seems to be valid to me?

`Error: Parameter #1 $data of method Magento\Framework\App\ActionFactory::create() expects array, string given.`
This seems to be untrue, the factory expects a string as far as I can see.

**Comment by shochdoerfer** [comment]
@rikwillems let me check later this week, I am currently traveling and don't have access to all the tools :)

**Comment by shochdoerfer** [comment]
@rikwillems I also think you can remove the `Ignored error pattern ~Parameter #3 \$data` from PHPStan's `ignoreErrors` configuration, probably something that was fixed in a recent Magento version.

For the other 2 errors I don't understand why those happen. You could try to update the `bitexpert/phpstan-magento` dependency to the latest version and see if the errors disappear. Also, it might make sense to upgrade PHPStan to a more recent version, the used version 1.7 is rather old. If that does not help, I would add both errors the `ignoreErrors` configuration. Given both are not showstoppers, that would be "ok" for me.

**Comment by rikwillems** [comment]
@shochdoerfer I removed the ignored error. The other two are solved by upgrading PHPStan.

**Comment by shochdoerfer** [comment]
Awesome! Thx.

**Pull request merged**
